### ISSUE TITLE
Worth updating / starting over?

### ISSUE THREAD

**Issue by svpernova09** [memphisphp/larastrap#16]
I've started a few projects here and there, and found myself missing this kind of bootstrapped starter package. 

I've got so far as to build a [package of Homestead that you can install per project](https://github.com/svpernova09/homesteadskeleton)

Today I started another project where it would have been nice to have a skeleton envoy config in place.

Thoughts?

**Comment by dan9186** [comment]
Define what you mean by starting over? Are you just referring to "catching up with the times" or do mean something like completely redoing the whole effort in another entirely different direction?

Personally I'd be game for either way, just trying to get an understanding of what you had in mind.

**Comment by svpernova09** [comment]
I think the direction is fine, where the direction would be to provide a starting point for a project beyond what ```laravel new project``` or a composer install would give you. 

I'm just curious if others watching this repo would still find use it such a thing.

**Comment by dan9186** [comment]
Ok cool.  Yeah when I went to start a side project the other day I found myself really wanting this again.  I'd be interested in it, though I don't if anyone else is "watching" this one.

**Comment by svpernova09** [comment]
Master has been updated for Laravel 5. Tagged 1.0.0 for 4.1.x if it's ever needed. Tagged 2.0.0 for 5.1 and beyond.
